### ISSUE TITLE
Issue when importing dictlearn?

### ISSUE THREAD

**Issue by ZitongYang** [permfl/dictlearn#2]
Hi, I encountered the following error when importing dictlearn. I have tried to reinstall the package in setup.py but still not working.

```
import dictlearn
Traceback (most recent call last):
  File "/Users/zitongyang/Documents/overcomplete/experiments/dictlearn/dictlearn/__init__.py", line 84, in <module>
    ___SETUP___
NameError: name '___SETUP___' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zitongyang/Documents/overcomplete/experiments/dictlearn/dictlearn/__init__.py", line 92, in <module>
    from .algorithms import (
  File "/Users/zitongyang/Documents/overcomplete/experiments/dictlearn/dictlearn/algorithms.py", line 6, in <module>
    from . import optimize, inpaint, sparse
  File "/Users/zitongyang/Documents/overcomplete/experiments/dictlearn/dictlearn/optimize.py", line 10, in <module>
    from . import sparse, preprocess
  File "/Users/zitongyang/Documents/overcomplete/experiments/dictlearn/dictlearn/sparse.py", line 13, in <module>
    from ._dictlearn import _dictlearn
  File "/Users/zitongyang/Documents/overcomplete/experiments/dictlearn/dictlearn/_dictlearn/__init__.py", line 1, in <module>
    from . import _dictlearn
ImportError: cannot import name '_dictlearn' from 'dictlearn._dictlearn' (/Users/zitongyang/Documents/overcomplete/experiments/dictlearn/dictlearn/_dictlearn/__init__.py)
```

**Comment by permfl** [comment]
It looks like the package didn't install/build correctly. The C extensions, `_dictlearn`,  fails to import. 

Try installing again with `$ python setup.py install`. If that doesn't  fix the issue, try building the extensions directly with `$ python setup.py build_ext`

**Comment by ZitongYang** [comment]
Problem solved now. Thanks a lot!

**Comment by chauhanmahavir** [comment]
Hello I have same problem can you help me i tried both thing python setup.py install and python setup.py build_ext. While i am importing dictlearn then i will get same error

**Comment by JorgeNustes** [comment]
Hi, I am getting the same error after running `import dictlearn`. I install the package using `python setup.py install` and tried with `python setup.py build_ext` but still gives an error. 

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
/content/dictlearn/dictlearn/__init__.py in <module>()
     83 try:
---> 84     ___SETUP___
     85     print('Installing dictlearn...')

NameError: name '___SETUP___' is not defined

<ipython-input-5-e8373b45b542> in <module>()
----> 1 import dictlearn

/content/dictlearn/dictlearn/__init__.py in <module>()
     90     #### TODO ####
     91     # Speed up imports: This is way to slow!
---> 92     from .algorithms import (
     93         Trainer, ImageTrainer, Denoise, Inpaint, ksvd_denoise
     94     )

/content/dictlearn/dictlearn/algorithms.py in <module>()
      4 import math
      5 import numpy as np
----> 6 from . import optimize, inpaint, sparse
      7 from .preprocess import Patches
      8 from .utils import dct_dict, random_dictionary, imread

/content/dictlearn/dictlearn/optimize.py in <module>()
      8 from scipy import linalg
      9 
---> 10 from . import sparse, preprocess
     11 
     12 """

/content/dictlearn/dictlearn/sparse.py in <module>()
     11 from . import filters
     12 from . import preprocess
---> 13 from ._dictlearn import _dictlearn
     14 
     15 

/content/dictlearn/dictlearn/_dictlearn/__init__.py in <module>()
----> 1 from . import _dictlearn
      2 from . import hessian

ImportError: cannot import name '_dictlearn'

```

**Comment by aldosarimo** [comment]
I ran into the same error, so I tried to import dictlearn on Jupyter Notebook, and the problem is resolved!

**Comment by akshatdalton** [comment]
Hi, I am trying to install this and ran into the same errors as others. Can someone please help me that what other things should I try?
I have done: 
1. `virtualenv venv`
2. `source venv/bin/activate`
3. `pip install -r requirements.txt`
4. `python2 setup.py install`
5. `python2 setup.py build_ext`
But still doesn't work when I try to run `pytest tests`

<details>
  <summary>Error log</summary>

  ```
  ========================================================= test session starts ==========================================================
platform linux -- Python 3.6.9, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/akshat/OpenSource/dictlearn
plugins: cov-3.0.0
collected 4 items / 8 errors                                                                                                           

================================================================ ERRORS ================================================================
______________________________________________ ERROR collecting tests/test__dictlearn.py _______________________________________________
ImportError while importing test module '/home/akshat/OpenSource/dictlearn/tests/test__dictlearn.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/__init__.py:84: in <module>
    ___SETUP___
E   NameError: name '___SETUP___' is not defined

During handling of the above exception, another exception occurred:
/usr/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test__dictlearn.py:8: in <module>
    from dictlearn import utils, algorithms, filters, preprocess
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/__init__.py:92: in <module>
    from .algorithms import (
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/algorithms.py:6: in <module>
    from . import optimize, inpaint, sparse
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/optimize.py:10: in <module>
    from . import sparse, preprocess
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/sparse.py:13: in <module>
    from ._dictlearn import _dictlearn
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/_dictlearn/__init__.py:1: in <module>
    from . import _dictlearn
E   ImportError: /home/akshat/OpenSource/dictlearn/venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/_dictlearn/_dictlearn.cpython-36m-x86_64-linux-gnu.so: undefined symbol: omp_get_thread_num
________________________________________________ ERROR collecting tests/test_filters.py ________________________________________________
ImportError while importing test module '/home/akshat/OpenSource/dictlearn/tests/test_filters.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/__init__.py:84: in <module>
    ___SETUP___
E   NameError: name '___SETUP___' is not defined

During handling of the above exception, another exception occurred:
/usr/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_filters.py:2: in <module>
    from dictlearn import filters
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/__init__.py:92: in <module>
    from .algorithms import (
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/algorithms.py:6: in <module>
    from . import optimize, inpaint, sparse
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/optimize.py:10: in <module>
    from . import sparse, preprocess
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/sparse.py:13: in <module>
    from ._dictlearn import _dictlearn
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/_dictlearn/__init__.py:1: in <module>
    from . import _dictlearn
E   ImportError: /home/akshat/OpenSource/dictlearn/venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/_dictlearn/_dictlearn.cpython-36m-x86_64-linux-gnu.so: undefined symbol: omp_get_thread_num
________________________________________________ ERROR collecting tests/test_kernels.py ________________________________________________
ImportError while importing test module '/home/akshat/OpenSource/dictlearn/tests/test_kernels.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/__init__.py:84: in <module>
    ___SETUP___
E   NameError: name '___SETUP___' is not defined

During handling of the above exception, another exception occurred:
/usr/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_kernels.py:2: in <module>
    from dictlearn import kernels
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/__init__.py:92: in <module>
    from .algorithms import (
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/algorithms.py:6: in <module>
    from . import optimize, inpaint, sparse
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/optimize.py:10: in <module>
    from . import sparse, preprocess
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/sparse.py:13: in <module>
    from ._dictlearn import _dictlearn
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/_dictlearn/__init__.py:1: in <module>
    from . import _dictlearn
E   ImportError: /home/akshat/OpenSource/dictlearn/venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/_dictlearn/_dictlearn.cpython-36m-x86_64-linux-gnu.so: undefined symbol: omp_get_thread_num
________________________________________________ ERROR collecting tests/test_linalg.py _________________________________________________
ImportError while importing test module '/home/akshat/OpenSource/dictlearn/tests/test_linalg.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/__init__.py:84: in <module>
    ___SETUP___
E   NameError: name '___SETUP___' is not defined

During handling of the above exception, another exception occurred:
/usr/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_linalg.py:2: in <module>
    from dictlearn.linalg import *
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/__init__.py:92: in <module>
    from .algorithms import (
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/algorithms.py:6: in <module>
    from . import optimize, inpaint, sparse
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/optimize.py:10: in <module>
    from . import sparse, preprocess
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/sparse.py:13: in <module>
    from ._dictlearn import _dictlearn
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/_dictlearn/__init__.py:1: in <module>
    from . import _dictlearn
E   ImportError: /home/akshat/OpenSource/dictlearn/venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/_dictlearn/_dictlearn.cpython-36m-x86_64-linux-gnu.so: undefined symbol: omp_get_thread_num
_______________________________________________ ERROR collecting tests/test_optimize.py ________________________________________________
ImportError while importing test module '/home/akshat/OpenSource/dictlearn/tests/test_optimize.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/__init__.py:84: in <module>
    ___SETUP___
E   NameError: name '___SETUP___' is not defined

During handling of the above exception, another exception occurred:
/usr/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_optimize.py:5: in <module>
    from dictlearn import optimize
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/__init__.py:92: in <module>
    from .algorithms import (
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/algorithms.py:6: in <module>
    from . import optimize, inpaint, sparse
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/optimize.py:10: in <module>
    from . import sparse, preprocess
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/sparse.py:13: in <module>
    from ._dictlearn import _dictlearn
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/_dictlearn/__init__.py:1: in <module>
    from . import _dictlearn
E   ImportError: /home/akshat/OpenSource/dictlearn/venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/_dictlearn/_dictlearn.cpython-36m-x86_64-linux-gnu.so: undefined symbol: omp_get_thread_num
______________________________________________ ERROR collecting tests/test_preprocess.py _______________________________________________
ImportError while importing test module '/home/akshat/OpenSource/dictlearn/tests/test_preprocess.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/__init__.py:84: in <module>
    ___SETUP___
E   NameError: name '___SETUP___' is not defined

During handling of the above exception, another exception occurred:
/usr/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_preprocess.py:3: in <module>
    from dictlearn import preprocess
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/__init__.py:92: in <module>
    from .algorithms import (
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/algorithms.py:6: in <module>
    from . import optimize, inpaint, sparse
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/optimize.py:10: in <module>
    from . import sparse, preprocess
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/sparse.py:13: in <module>
    from ._dictlearn import _dictlearn
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/_dictlearn/__init__.py:1: in <module>
    from . import _dictlearn
E   ImportError: /home/akshat/OpenSource/dictlearn/venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/_dictlearn/_dictlearn.cpython-36m-x86_64-linux-gnu.so: undefined symbol: omp_get_thread_num
________________________________________________ ERROR collecting tests/test_sparse.py _________________________________________________
ImportError while importing test module '/home/akshat/OpenSource/dictlearn/tests/test_sparse.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/__init__.py:84: in <module>
    ___SETUP___
E   NameError: name '___SETUP___' is not defined

During handling of the above exception, another exception occurred:
/usr/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_sparse.py:5: in <module>
    from dictlearn import sparse
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/__init__.py:92: in <module>
    from .algorithms import (
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/algorithms.py:6: in <module>
    from . import optimize, inpaint, sparse
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/optimize.py:10: in <module>
    from . import sparse, preprocess
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/sparse.py:13: in <module>
    from ._dictlearn import _dictlearn
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/_dictlearn/__init__.py:1: in <module>
    from . import _dictlearn
E   ImportError: /home/akshat/OpenSource/dictlearn/venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/_dictlearn/_dictlearn.cpython-36m-x86_64-linux-gnu.so: undefined symbol: omp_get_thread_num
_________________________________________________ ERROR collecting tests/test_utils.py _________________________________________________
ImportError while importing test module '/home/akshat/OpenSource/dictlearn/tests/test_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/__init__.py:84: in <module>
    ___SETUP___
E   NameError: name '___SETUP___' is not defined

During handling of the above exception, another exception occurred:
/usr/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_utils.py:5: in <module>
    from dictlearn import utils
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/__init__.py:92: in <module>
    from .algorithms import (
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/algorithms.py:6: in <module>
    from . import optimize, inpaint, sparse
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/optimize.py:10: in <module>
    from . import sparse, preprocess
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/sparse.py:13: in <module>
    from ._dictlearn import _dictlearn
venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/_dictlearn/__init__.py:1: in <module>
    from . import _dictlearn
E   ImportError: /home/akshat/OpenSource/dictlearn/venv/lib/python3.6/site-packages/dictlearn-0.0.1-py3.6-linux-x86_64.egg/dictlearn/_dictlearn/_dictlearn.cpython-36m-x86_64-linux-gnu.so: undefined symbol: omp_get_thread_num
======================================================= short test summary info ========================================================
ERROR tests/test__dictlearn.py
ERROR tests/test_filters.py
ERROR tests/test_kernels.py
ERROR tests/test_linalg.py
ERROR tests/test_optimize.py
ERROR tests/test_preprocess.py
ERROR tests/test_sparse.py
ERROR tests/test_utils.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 8 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
========================================================== 8 errors in 14.90s ==========================================================
  ```
</details>

Perhaps @aldosarimo you can tell us how did you resolve the error in your Jupyter Notebook?
@permfl
